### ISSUE TITLE
META file requests dependencies on broken modules

### ISSUE THREAD

**Issue by zoffixznet** [scriptkitties/perl6-App-Cpan6#34]
The META file locks the dependency on 0.9.6 version of JSON::Fast, which has numerous bugs, including reliance on a Rakudo bug that's fixed in latest Rakudo.

For that reason, this module won't be installable on Rakudo 2018.03 and later.

**Comment by Tyil** [comment]
I've asked around (on multiple occasions) on how to best specify the version for my dependencies, taking [Semantic Versioning](https://semver.org/) into account. Every time with no reply, sadly.

I would like to depend on a given version, up until the next major release. In this case, that means I want to depend on `JSON::Fast` version 0.9.11 or higher, but not 1.0.0 or higher.

My intent was to depend on versions in this manner, but since I never got a reply on how to achieve this, I opted for simply depending on a version that worked for me at the time, hoping to fix it whenever I got a viable solution. I'd very much like to fix it properly here this time around, rather than procrastinate on it even more. Would you be able to tell me how to specify the versioning limits that I want?

**Comment by zoffixznet** [comment]
> Would you be able to tell me how to specify the versioning limits that I want?

Not really. In pure Perl 6 it'd be `v1.*.* & v0.9.11+` but I doubt zef currently supports even one of these syntaxes.

**Comment by AlexDaniel** [comment]
Would be nice if the PR in #35 was merged.

@Tyil maybe you can open a zef issue asking to support what you need?

**Comment by Tyil** [comment]
@AlexDaniel I hadn't merged it yet because of a failing test, but this has been discussed on `#perl6`, it's nothing important, so I'll be merging it in a couple minutes. I'll open an issue on zef to look into the possibilities for version identifiers that would work for me. For now, I'll set it to a minimum version and allow any higher version, since that's the closest to what I wanted.

**Comment by AlexDaniel** [comment]
@Tyil OK! Thank you very much!
